package com.example.miniproyecto2sudokuedadlepr.controller;

import com.example.miniproyecto2sudokuedadlepr.view.SudokuGuideStage;
import com.example.miniproyecto2sudokuedadlepr.view.SudokuStartStage;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;

import java.io.IOException;

/**
 * Controller class for the help screen of the Sudoku application.
 * <p>
 * This controller manages user interactions within the help window,
 * such as navigating back to the main menu.
 */
public class SudokuGuideController {

    /**
     * Handles the action of returning to the main menu.
     * <p>
     * When triggered, this method opens the {@link SudokuStartStage}
     * and closes the current {@link SudokuGuideStage}.
     *
     * @param event the {@link ActionEvent} generated by the "Back" button click.
     */
    @FXML
    void returnToMenu(ActionEvent event) {
        try {
            SudokuStartStage.getOrCreateStage();
            SudokuGuideStage.closeStage();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
