package com.example.miniproyecto2sudokuedadlepr.controller;

import com.example.miniproyecto2sudokuedadlepr.view.SudokuEndStage;
import com.example.miniproyecto2sudokuedadlepr.view.SudokuStartStage;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;

import java.io.IOException;

/**
 * Controller class for the final screen of the Sudoku application.
 * <p>
 * This controller manages user interactions on the "Final" stage,
 * such as returning to the main menu after the game ends.
 */
public class SudokuEndController {

    /**
     * Handles the action of returning to the main menu.
     * <p>
     * When triggered, this method opens the {@link SudokuStartStage}
     * and closes the current {@link SudokuEndStage}.
     *
     * @param event the {@link ActionEvent} generated by the menu button click.
     */
    @FXML
    void returnToMenu(ActionEvent event) {
        try {
            SudokuStartStage.getOrCreateStage();
            SudokuEndStage.closeStage();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
