package com.example.miniproyecto2sudokuedadlepr.controller;

import com.example.miniproyecto2sudokuedadlepr.model.user.PlayerData;
import com.example.miniproyecto2sudokuedadlepr.view.SudokuGuideStage;
import com.example.miniproyecto2sudokuedadlepr.view.SudokuPlayStage;
import com.example.miniproyecto2sudokuedadlepr.view.SudokuStartStage;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.TextField;

import java.io.IOException;


/**
 * Controller class for the welcome screen of the Sudoku application.
 * <p>
 * This controller manages the main menu interactions, including starting a new game,
 * opening the help window, and exiting the application.
 */
public class SudokuStartController {

    /** Text field for entering the user's playerName. */
    @FXML
    private TextField playerNameTxt;

    /**
     * Handles the action of starting the game.
     * <p>
     * If a playerName is entered, this method creates a new {@link PlayerData},
     * passes it to the {@link SudokuPlayStage} controller, and then
     * closes the current welcome stage.
     *
     * @param event the {@link ActionEvent} generated by clicking the "Play" button.
     */
    @FXML
    void startNewRound(ActionEvent event) {
        String playerName = playerNameTxt.getText().trim();
        try {
            if (!playerName.equals("")) {
                SudokuPlayStage.getOrCreateStage().getController().assignPlayer(new PlayerData(playerName));
                SudokuStartStage.closeStage();
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * Handles the action of exiting the application.
     * <p>
     * When triggered, this method closes the {@link SudokuStartStage}.
     *
     * @param event the {@link ActionEvent} generated by clicking the "Leave" button.
     */
    @FXML
    void closeApp(ActionEvent event) {
        SudokuStartStage.closeStage();
    }

    /**
     * Handles the action of opening the help screen.
     * <p>
     * When triggered, this method opens the {@link SudokuGuideStage}
     * and closes the current {@link SudokuStartStage}.
     *
     * @param event the {@link ActionEvent} generated by clicking the "Help" button.
     */
    @FXML
    void openGuideScreen(ActionEvent event) {
        try {
            SudokuGuideStage.getOrCreateStage();
            SudokuStartStage.closeStage();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
